"""empty message

Revision ID: 2e1932c88a8e
Revises: c445af2a3b3b
Create Date: 2025-01-06 10:36:58.553066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1932c88a8e'
down_revision = 'c445af2a3b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rpc_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('explorer_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('chain_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('chain_id')
        batch_op.drop_column('explorer_url')
        batch_op.drop_column('rpc_url')

    # ### end Alembic commands ###
