"""empty message

Revision ID: 5ff93cbf3cc1
Revises: f774f7c91c2a
Create Date: 2025-01-18 15:23:04.381731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff93cbf3cc1'
down_revision = 'f774f7c91c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gas_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('gas_limit')

    # ### end Alembic commands ###
