"""empty message

Revision ID: 6eff7cb8a093
Revises: a52d5f6ce7d1
Create Date: 2025-01-18 12:46:53.415689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eff7cb8a093'
down_revision = 'a52d5f6ce7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
