"""empty message

Revision ID: 791428bbeb88
Revises: 1bf33becd4e2
Create Date: 2025-01-11 15:59:57.056075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791428bbeb88'
down_revision = '1bf33becd4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_url', sa.String(length=320), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('background_url')

    # ### end Alembic commands ###
