"""empty message

Revision ID: 884cc2bc5abe
Revises: c01910dd1961
Create Date: 2025-01-11 16:22:04.860817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '884cc2bc5abe'
down_revision = 'c01910dd1961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_details', schema=None) as batch_op:
        batch_op.drop_column('qr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr', mysql.VARCHAR(length=400), nullable=True))

    # ### end Alembic commands ###
