"""empty message

Revision ID: a52d5f6ce7d1
Revises: ca29ecbab9a3
Create Date: 2025-01-11 23:45:30.822604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52d5f6ce7d1'
down_revision = 'ca29ecbab9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_key', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('price_key')

    # ### end Alembic commands ###
