"""empty message

Revision ID: bd03d4e0c65d
Revises: 2e1932c88a8e
Create Date: 2025-01-09 13:56:32.245064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd03d4e0c65d'
down_revision = '2e1932c88a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('native', sa.Boolean(), nullable=True),
    sa.Column('contract_address', sa.String(length=120), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
