"""empty message

Revision ID: c01910dd1961
Revises: 791428bbeb88
Create Date: 2025-01-11 16:08:50.549835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01910dd1961'
down_revision = '791428bbeb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_details', schema=None) as batch_op:
        batch_op.drop_column('qr')

    # ### end Alembic commands ###
