"""empty message

Revision ID: c445af2a3b3b
Revises: 
Create Date: 2025-01-06 10:10:57.093454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c445af2a3b3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('derive_path', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    # ### end Alembic commands ###
