"""empty message

Revision ID: ca29ecbab9a3
Revises: 47648638ea0a
Create Date: 2025-01-11 23:05:54.797444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca29ecbab9a3'
down_revision = '47648638ea0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_column('index')

    with op.batch_alter_table('network', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
